# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-27 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20190527_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mehnurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
